name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker fastapi-hello
      run: docker build -t saktisundar2009/fastapi-hello . ; docker login -u saktisundar2009 -p Lucky555$ ;   docker push saktisundar2009/fastapi-hello:latest ;
